stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Build job is running"
    - echo "Commit Ref Name: $CI_COMMIT_REF_NAME"
    - echo "Job ID: $CI_JOB_ID"
    - echo "Pipeline ID: $CI_PIPELINE_ID"

deploy:
  stage: deploy
  script:
    - echo "Deploy job is running"
    - echo "Commit Ref Name: $CI_COMMIT_REF_NAME"
    - echo "Job ID: $CI_JOB_ID"
    - echo "Pipeline ID: $CI_PIPELINE_ID"
  variables:
    DEPLOY_ENV: "production"
